baseURL = "https://PranavGopalak.github.io/DataWebsiteProject-Hugo/"
languageCode = "en-us"
title = "Data Website Project - Hugo"
theme = "ananke"

disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
pagination.pagerSize = 10
