baseURL = "https://PranavGopalak.github.io/DataWebsiteProject-Hugo/"
languageCode = "en-us"
title = "Data Website Project - Hugo"
theme = "your-theme-name"  # Replace with your actual theme name, e.g., "ananke"
