name: Hugo Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.139.3'  # Specify a stable Hugo version

      - name: Build Hugo Site
        run: hugo --config hugo.toml --minify  # Specify your config file

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}  # Ensure this secret is set
          publish_dir: ./public  # Hugo's default output directory
